server {
    listen 80;
    server_name localhost;

    # Раздаем статику Vue
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Поддержка маршрутизации Vue Router (если понадобится)
        try_files $uri $uri/ /index.html;
    }

    # Проксируем запросы к API на бэкенд-контейнер
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
